---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-2
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: busybox-2
  template:
    metadata:
      labels:
        appname: busybox-2
    spec:
      containers:
        - name: logger
          image: quay.io/nirsof/busybox:stable
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              emit() {
                  echo "$(date) $1" | tee -a /var/log/ramen.log
                  sync
              }
              trap "emit STOP; exit" TERM
              emit START
              while true; do
                  sleep 10 & wait
                  emit UPDATE
              done
          volumeMounts:
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: varlog
          persistentVolumeClaim:
            claimName: busybox-pvc-2
